---
title: "Liver_2weekdel_Mapping_Features"
author: "Alvaro Regano"
date: "13/01/2022"
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(
  echo = TRUE, out.width = "200%", fig.align = "center",fig.width = 16,fig.height = 7,
  message = FALSE, warning = FALSE
)
#knitr::opts_knit$set(root.dir= normalizePath('..'))
#knitr::opts_chunk$set(error = FALSE)
options(width = 9000)

```


```{r library, echo=FALSE}
library(Seurat)
library(ggplot2)
library("knitr")
library("rmarkdown")
library("yaml")
library("patchwork")
library("dittoSeq")
library("magick")
library("RColorBrewer")
```

# Objective

I will produce some plots Rui asked me for the writing of the paper.


##	Global UMAP showing the different Clusters


```{r carlos, fig.asp=0.8, echo=FALSE}

my_palette_Rui_colors <- c("#E95A74", "#50B6EF", "#45FF8E", "#F4A753", "#A80519", "#880088", "#E28CF4", "#C1B80C","#FC0808",  "#0E47D8")

custom_rdylblu_palette <- c("#005AD9", "#0070FF", "#FFE135", "#FFDA13", "#E60026", "#C60012")

BYG <- c("#0000FF", "#3838C6", "#71718D", "#AAAA55", "#E2E21C", "#FFE200", "#FFAA00", "#FF7100", "#FF3800", "#FF0000")

grey_BYG <- c( "#D0C9D7", "#0000FF", "#3838C6", "#71718D", "#AAAA55", "#E2E21C", "#FFE200", "#FFAA00", "#FF7100", "#FF3800", "#FF0000")

rui_palette <- c( "#D0C9D7", "#71718D", "#AAAA55", "#E2E21C", "#FFE200", "#FFAA00", "#FF7100", "#FF3800", "#FF0000")

macarena_palette <- c("#FDDC85", "#6E2914")

Bestholtz_palette <- c("#DEDAD6", "#FEE392", "#FEC44E", "#FE9929", "#ED6F11", "#CC4C17", "#993411", "#65260C")

Liver <- readRDS("../rds/")

DefaultAssay(Liver) <- "RNA"

DimPlot(Liver, pt.size = 2, group.by = "predicted.id", label = T, label.size = 10, label.box = TRUE, cols = my_palette_Rui_colors)+ NoAxes() + NoLegend() + scale_x_reverse()


```

```{r carlosa, fig.asp=0.8, echo=FALSE}

DimPlot(Liver, pt.size = 2, group.by = "predicted.id", cols = my_palette_Rui_colors)+ NoAxes() + scale_x_reverse() + theme(legend.text = element_text(size = 20))


```


## Global UMAP by Conditions

```{r carlos2, fig.asp=0.8, echo=FALSE}

DimPlot(Liver, group.by = "Condition", pt.size = 2, label.size = 8)+ NoAxes()+ scale_x_reverse()+ theme(legend.text = element_text(size = 20))


```

```{r carlos4, fig.asp=0.8, echo=FALSE}

DimPlot(Liver, group.by = "Condition", pt.size = 2, label = T,label.box = TRUE, label.size = 8, repel = T)+ NoAxes()+ NoLegend()+ scale_x_reverse()

```


```{r carlos3, fig.height=5, fig.width=20, echo=FALSE}

DimPlot(Liver, split.by = "Condition", group.by = "predicted.id", pt.size = 1.2, cols = my_palette_Rui_colors)+ NoAxes()+ scale_x_reverse()
```



## Features Plots of the 6 Conditions splitted up.


```{r f, fig.width=35, fig.height= 70, echo=FALSE}

genes <- list(c("ODC1", "KCNE3", "MKI67", "WNT2", "MSR1", "LTBP4", "RSPO3", "GJA5", "CDKN1A", "STMN1", "VEGFA", "ESM1", "HES1", "MYC"))
genes <- as.data.frame(genes)


#  Script

myplots <- vector('list', nrow(genes))


for (i in 1:nrow(genes)) {
  
  p21 <- FeaturePlot(Liver, pt.size = 1.3, features = genes[i, 1], order = T, combine = F)

  p22 <- FeaturePlot(Liver, split.by = "Condition", order = T,features = genes[i, 1], combine = F)

  p21 <- lapply(X = p21, FUN = function(p) p + NoAxes()+ scale_x_reverse()+ scale_fill_gradientn(Bestholtz_palette))

  p22 <- lapply(X = p22, FUN = function(p) p + NoLegend() + NoAxes()+ scale_x_reverse()+ scale_fill_gradientn(Bestholtz_palette))

  p21 <- Reduce( `+`, p21 )+patchwork::plot_layout( ncol = 1 )

  p22 <- Reduce( `+`, p22 )+patchwork::plot_layout( ncol = 6 )

  p23 <- list(p21, p22)


  design <- c(patchwork::area(1, 1, 1, 1), patchwork::area(1, 2, 1, 7))

  p24 <- Reduce( `+`,  p23)+patchwork::plot_layout(design = design)

  
  myplots[[i]] <- local({
    i <- i
    p24
  })
  
  
}

p25 <- patchwork::wrap_plots(myplots, ncol = 1)

#myplots[1:nrow(genes)] + patchwork::plot_layout(byrow = T, widths = 25, heights = 5)
p25


# p25 <- CombinePlots(plots = myplots, ncol = 1)
# p25

```


##	Barplots

```{r b, fig.height=10, fig.width=8, echo=FALSE}

dittoBarPlot(Liver, var = "predicted.id", group.by = "Condition", color.panel = my_palette_Rui_colors, xlab = NULL, main = NULL)+ theme(axis.text=element_text(size=18), axis.title = element_text(size = 20), legend.text = element_text(size = 16))

```

```{r b2, fig.height=10, fig.width=8, echo=FALSE}

dittoBarPlot(Liver, var = "predicted.id", group.by = "Condition", scale = "count", color.panel = my_palette_Rui_colors, xlab = NULL, main = NULL)+ theme(axis.text=element_text(size=18), axis.title = element_text(size = 20), legend.text = element_text(size = 16))

```


```{r barplot, fig.height=10, fig.width=4, echo=FALSE}

dittoBarPlot(Liver, var = "predicted.id", group.by = "orig.ident", scale = "count", color.panel = my_palette_Rui_colors, xlab = NULL, main = NULL)+ theme(axis.text=element_text(size=18), axis.title = element_text(size = 20), legend.text = element_text(size = 16))

```

```{r session, fig.height=10, fig.width=4, echo=FALSE}

sessionInfo()

```
